CREATE TABLE batches
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    batch_number       BIGINT                                  NOT NULL,
    manufacturing_date date                                    NOT NULL,
    expiration_date    date                                    NOT NULL,
    initial_quantity   INTEGER                                 NOT NULL,
    current_quantity   INTEGER                                 NOT NULL,
    batch_status       VARCHAR(255),
    medication_id      BIGINT,
    CONSTRAINT pk_batches PRIMARY KEY (id)
);

ALTER TABLE batches
    ADD CONSTRAINT FK_BATCHES_ON_MEDICATION FOREIGN KEY (medication_id) REFERENCES medicaments (id);


CREATE TABLE medicaments
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    description         TEXT,
    medicament_category VARCHAR(255)                            NOT NULL,
    unit_of_measure     VARCHAR(255)                            NOT NULL,
    cold_chain          BOOLEAN                                 NOT NULL,
    volume              DECIMAL(10, 2)                          NOT NULL,
    CONSTRAINT pk_medicaments PRIMARY KEY (id)
)

CREATE TABLE stock_entries
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entry_date date                                    NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    supplier   VARCHAR(255)                            NOT NULL,
    batch_id   BIGINT,
    CONSTRAINT pk_stock_entries PRIMARY KEY (id)
);

ALTER TABLE stock_entries
    ADD CONSTRAINT FK_STOCK_ENTRIES_ON_BATCH FOREIGN KEY (batch_id) REFERENCES batches (id);

CREATE TABLE stock_exits
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    exit_date   date                                    NOT NULL,
    quantity    INTEGER                                 NOT NULL,
    exit_reason VARCHAR(255),
    batch_id    BIGINT,
    CONSTRAINT pk_stock_exits PRIMARY KEY (id)
);

ALTER TABLE stock_exits
    ADD CONSTRAINT FK_STOCK_EXITS_ON_BATCH FOREIGN KEY (batch_id) REFERENCES batches (id);


CREATE TABLE expiration_alerts
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    alert_date              date                                    NOT NULL,
    days_until_expiration   INTEGER                                 NOT NULL,
    expiration_alert_status VARCHAR(255),
    batch_id                BIGINT,
    CONSTRAINT pk_expiration_alerts PRIMARY KEY (id)
);

ALTER TABLE expiration_alerts
    ADD CONSTRAINT FK_EXPIRATION_ALERTS_ON_BATCH FOREIGN KEY (batch_id) REFERENCES batches (id);

CREATE INDEX idx_batch_expiration_active ON batches (expiration_date)
    WHERE batch_status = 'ACTIVE' AND current_quantity > 0;